stages:
  download:
    cmd: Rscript src/1_download.R
    deps:
    - src/1_download.R
    - http://ctdbase.org/downloads/
    outs:
    - download/
  build:
    cmd: Rscript src/2_build.R
    deps:
    - src/2_build.R
    - download/
    outs:
    - brick/
