stages:
  invalidate:
    cmd: sh stages/00_invalidate.sh
    deps:
    - stages/00_invalidate.sh
    outs:
    - checksum/
  download:
    cmd: Rscript stages/01_download.R
    deps:
    - stages/01_download.R
    - http://ctdbase.org/downloads/
    outs:
    - download/
  build:
    cmd: Rscript stages/02_build.R
    deps:
    - stages/02_build.R
    - download/
    outs:
    - brick/
